In [2]:
import random
import pandas as pd
import numpy as np
df = pd.read_csv('StudentsPerformance.csv')

In [4]:
#sort descending by index
df.sort_index(ascending=False,inplace=True)
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
999,female,group D,some college,free/reduced,none,77,86,86
998,female,group D,some college,standard,completed,68,78,77
997,female,group C,high school,free/reduced,completed,59,71,65
996,male,group C,high school,free/reduced,none,62,55,55
995,female,group E,master's degree,standard,completed,88,99,95

In [12]:
#rename one column
df = df.rename(columns={'gender':'Gender'})
df.head()

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
999,female,group D,some college,free/reduced,none,77,86,86
998,female,group D,some college,standard,completed,68,78,77
997,female,group C,high school,free/reduced,completed,59,71,65
996,male,group C,high school,free/reduced,none,62,55,55
995,female,group E,master's degree,standard,completed,88,99,95

In [16]:
#rename multiple columns
df = df.rename(columns= {'math score':'Maths_score',
                        'reading score':'Reading_score',
                        'writing score':'Writing_Score'})
df.head()

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,Maths_score,Reading_score,Writing_Score
999,female,group D,some college,free/reduced,none,77,86,86
998,female,group D,some college,standard,completed,68,78,77
997,female,group C,high school,free/reduced,completed,59,71,65
996,male,group C,high school,free/reduced,none,62,55,55
995,female,group E,master's degree,standard,completed,88,99,95

In [28]:
#rename index  0 1 and 2 and update df
df = pd.read_csv('StudentsPerformance.csv')
df.rename(index={0:'A',1:'B',2:'C'},inplace=True)
df.head(3)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
A,female,group B,bachelor's degree,standard,none,72,72,74
B,female,group C,some college,standard,completed,69,90,88
C,female,group B,master's degree,standard,none,90,95,93